### ISSUE TITLE
format of caveman.csv

### ISSUE THREAD

**Issue by Tim0thy1** [cancerit/ascatNgs#81] opened 2018-12-11 10:54 UTC
Hi,drjsanger 

I have tried to run ascatngs to call somatic CNV. I doubt that the result of  'copynumber.caveman.csv' file.

1,1,13116,45966582,2,1,4,1
2,1,45968504,46871875,2,1,2,0
3,1,46873039,121484236,2,1,4,1
4,1,142535439,151385859,2,1,3,1
5,1,151387508,169700961,2,1,4,2
6,1,169702278,226553473,2,1,3,1
7,1,226555302,234529519,2,1,5,2
8,1,234530740,249239902,2,1,4,2
9,2,10587,61412559,2,1,5,1
10,2,61413723,61418343,2,1,4,1
11,2,61420140,61436930,2,1,3,0
12,2,61439206,61448493,2,1,4,0
13,2,61450454,61473148,2,1,2,0
14,2,61475577,61564887,2,1,4,0
15,2,61566536,61604383,2,1,3,0
16,2,61605614,61620547,2,1,4,0
17,2,61622251,61646631,2,1,3,0
18,2,61647901,61705663,2,1,4,0
....
578,X,48973297,49009508,1,0,3,0
579,X,49013680,49019748,1,0,4,0
580,X,49021052,49034048,1,0,2,0
581,X,49035816,49038983,1,0,1,0
582,X,49040034,49060744,1,0,2,0
583,X,49062007,49068227,1,0,4,0
584,X,49069366,49074636,1,0,3,0
585,X,49077072,49082130,1,0,1,0
586,X,49084492,49096067,1,0,2,0
587,X,49098631,49103097,1,0,1,0
588,X,49105610,49122026,1,0,3,0
589,X,49126714,49136340,1,0,1,0
590,X,49137916,154929412,1,0,3,0
591,Y,2657176,28769098,1,0,0,0

For chr[1-22] , Copy Number = 
minor allele (1) of normal sample  +  
major allele (2)  of normal sample  = 3  , but my sample from a diploid human cell .  Are there any problem in that?

**Comment by wanhui5867** [comment] 2020-07-03 15:46
Hi Tim,

I also have this doubt. It seems that the number of Major copy number in the *caveman.csv should be Total copy number. Right?

**Comment by keiranmraine** [comment] 2020-07-03 16:09
Did you review the proposed solution from ASCAT before finalising the result as described in the protocols paper?

https://github.com/cancerit/ascatNgs/wiki

**Comment by wanhui5867** [comment] 2020-07-05 09:55
@keiranmraine  Hi, Keiran! Thanks for your quick response. 
I have read the 2010 ASCAT paper and 2016 ascatNgs paper, but I did not get your point. Does the "proposed solution" mean the good choose of purity and ploidy, or the explanation of major copy number = 2 and minor copy number = 1?
If it is the previous one, I think that it is not the cause because of the germline major_CN=2 in all of my samples. 
If it is the latter one, I did not find it. Maybe I missed the important information, could you point it out in detail?  Thanks in advance.

**Comment by keiranmraine** [comment] 2020-07-05 10:25
I was meaning did the ascat "sunrise" plot have multiple locations of deep blue, but looking deeper I believe you are correct.

This section of R generates the csv file:

https://github.com/cancerit/ascatNgs/blob/99ca9a4a8aee776592255ffec78ae7464ac62d9c/perl/share/ascat/runASCAT.R#L263-L277

I've delved into what we use for input into caveman, which should be total copynumber, and we use columns 4/6 (0 indexed):

```
perl -ne '@F=(split q{,}, $_)[1,2,3,4]; $F[1]-1; print join("\\t",@F)."\\n";' < $OUTDIR/*.copynumber.caveman.csv > $OUTDIR/norm.cn.bed
perl -ne '@F=(split q{,}, $_)[1,2,3,6]; $F[1]-1; print join("\\t",@F)."\\n";' < $OUTDIR/*.copynumber.caveman.csv > $OUTDIR/tum.cn.bed
```

It looks like the protocols paper has an error, we will add something to the Wiki to indicate this.

**Comment by wanhui5867** [comment] 2020-07-05 10:56
Yeah, if it is the total copy number, everything could be explained. Previously, I also confused the red line and green line are always in the same line in the ascat profile plot, but they are not same in the table. I think you can close this issue after adding this to Wiki.

Could I ask another question about copy number change? I open a new issue here: https://github.com/cancerit/ascatNgs/issues/95

**Comment by keiranmraine** [comment] 2020-07-05 11:49
Wiki updated with correction to format.

**Closed by keiranmraine** 2020-07-05 11:49 UTC
Labels: documentation
